//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicInventory.Models
{
    using System;
    using System.Collections.Generic;

    public class MusicList
    {
        public List<Music> musicList;
        public MusicList()
        {
            musicList = new List<Music>();
        }
    }

    public class Music
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Artist { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImageUrl { get; set; }

        public int Quantity = 1;
    }
}
